import AppLayout from "@/components/AppLayout";
import { Link } from "react-router-dom";
import { useState } from "react";
import { Bell, Search, ArrowUpRight, CheckCircle2, CircleAlert, XCircle, Newspaper, UserRound } from "lucide-react";
import { newsScans, NewsDomain } from "@/lib/fake-news-data";

export default function Dashboard() {
  const [domain, setDomain] = useState<"All" | NewsDomain>("All");
  const scans = domain === "All" ? newsScans : newsScans.filter((scan) => scan.domain === domain);
  const stats = [
    { label: "Likely real", value: newsScans.filter((scan) => scan.verdict === "Likely real").length, icon: CheckCircle2, color: "text-success" },
    { label: "Needs review", value: newsScans.filter((scan) => scan.verdict === "Needs review").length, icon: CircleAlert, color: "text-warning" },
    { label: "Likely fake", value: newsScans.filter((scan) => scan.verdict === "Likely fake").length, icon: XCircle, color: "text-destructive" },
  ];

  return <AppLayout><div className="p-6 lg:p-8 max-w-[1400px]">
    <div className="flex items-center justify-between mb-8"><div><h1 className="text-2xl font-display font-bold text-foreground">Good morning</h1><p className="text-muted-foreground mt-1">Your newsroom intelligence brief is ready.</p></div><div className="flex items-center gap-3"><div className="relative hidden md:block"><Search className="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" /><input placeholder="Search stories..." className="bg-card border border-input rounded-xl pl-10 pr-4 py-2.5 text-sm w-64 focus:outline-none focus:ring-2 focus:ring-accent/30" /></div><Link to="/user-panel" className="hidden sm:inline-flex items-center gap-2 rounded-xl border border-input bg-card px-3 py-2.5 text-sm font-semibold text-foreground hover:border-accent"><UserRound className="w-4 h-4 text-accent" />My workspace</Link><button className="relative p-2.5 rounded-xl bg-card border border-input"><Bell className="w-5 h-5 text-muted-foreground" /><span className="absolute top-1.5 right-1.5 w-2 h-2 rounded-full bg-destructive" /></button><Link to="/analyze" className="bg-accent text-accent-foreground px-4 py-2.5 rounded-xl text-sm font-semibold">Analyze story</Link></div></div>
    <div className="grid grid-cols-1 md:grid-cols-3 gap-4">{stats.map((stat) => <div key={stat.label} className="glass-card rounded-xl p-5"><div className="flex justify-between items-start"><div><p className="text-sm text-muted-foreground">{stat.label}</p><p className="text-3xl font-display font-bold text-foreground mt-2">{stat.value}</p></div><stat.icon className={`w-5 h-5 ${stat.color}`} /></div><p className="text-xs text-muted-foreground mt-4">of {newsScans.length} stories scanned</p></div>)}</div>
    <div className="mt-6 grid grid-cols-1 lg:grid-cols-[1.2fr_0.8fr] gap-6"><div className="glass-card rounded-xl overflow-hidden"><div className="px-6 py-5 border-b border-border flex items-center justify-between"><div><h2 className="font-display font-semibold text-foreground">Recent scans</h2><p className="text-sm text-muted-foreground mt-1">Latest credibility decisions across your desks.</p></div><Link to="/history" className="text-sm text-accent font-medium flex items-center gap-1">View history <ArrowUpRight className="w-3.5 h-3.5" /></Link></div><div className="px-6 py-4 flex gap-2 border-b border-border">{(["All", "Politics", "Sport"] as const).map((option) => <button key={option} onClick={() => setDomain(option)} className={`px-3 py-1.5 rounded-md text-xs font-semibold ${domain === option ? "bg-primary text-primary-foreground" : "bg-muted text-muted-foreground"}`}>{option}</button>)}</div><div className="divide-y divide-border">{scans.slice(0, 4).map((scan) => <div key={scan.id} className="px-6 py-4 flex items-center gap-3"><div className="w-8 h-8 rounded-lg bg-accent/10 flex items-center justify-center shrink-0"><Newspaper className="w-4 h-4 text-accent" /></div><div className="min-w-0 flex-1"><p className="text-sm font-medium text-foreground truncate">{scan.headline}</p><p className="text-xs text-muted-foreground mt-1">{scan.source} · {scan.domain}</p></div><span className={`text-xs font-semibold whitespace-nowrap ${scan.verdict === "Likely real" ? "text-success" : scan.verdict === "Likely fake" ? "text-destructive" : "text-warning"}`}>{scan.confidence}%</span></div>)}</div></div><div className="rounded-xl bg-primary p-6 text-primary-foreground"><p className="text-xs uppercase tracking-[0.16em] text-primary-foreground/60">Signal monitor</p><h2 className="text-2xl font-display font-bold mt-2">Keep context ahead of the click.</h2><p className="text-sm text-primary-foreground/70 mt-3 leading-relaxed">VerityDesk checks language, sourcing, and cross-story consistency for two high-impact desks.</p><div className="mt-8 space-y-4"><div className="flex justify-between text-sm"><span>Politics coverage</span><span>62%</span></div><div className="h-2 rounded-full bg-primary-foreground/15"><div className="h-full w-[62%] rounded-full bg-accent" /></div><div className="flex justify-between text-sm"><span>Sport coverage</span><span>38%</span></div><div className="h-2 rounded-full bg-primary-foreground/15"><div className="h-full w-[38%] rounded-full bg-warning" /></div></div></div></div>
  </div></AppLayout>;
}
