import { useMemo, useState } from "react";
import AppLayout from "@/components/AppLayout";
import { Search, SlidersHorizontal, CheckCircle2, CircleAlert, XCircle } from "lucide-react";
import { domainOptions, newsScans, Verdict } from "@/lib/fake-news-data";

const verdictIcon: Record<Verdict, typeof CheckCircle2> = { "Likely real": CheckCircle2, "Needs review": CircleAlert, "Likely fake": XCircle };

export default function ScanHistory() {
  const [query, setQuery] = useState("");
  const [domain, setDomain] = useState<(typeof domainOptions)[number]>("All domains");
  const filtered = useMemo(() => newsScans.filter((scan) => (domain === "All domains" || scan.domain === domain) && `${scan.headline} ${scan.source}`.toLowerCase().includes(query.toLowerCase())), [domain, query]);
  return <AppLayout><div className="p-6 lg:p-8 max-w-[1400px]"><div className="flex items-center justify-between mb-8"><div><h1 className="text-2xl font-display font-bold text-foreground">Scan history</h1><p className="text-muted-foreground text-sm mt-1">Review every story checked by your newsroom.</p></div><div className="flex items-center gap-2 text-sm text-muted-foreground"><SlidersHorizontal className="w-4 h-4" />{filtered.length} results</div></div><div className="glass-card rounded-xl overflow-hidden"><div className="p-4 border-b border-border flex flex-col md:flex-row gap-3"><div className="relative flex-1"><Search className="absolute left-3 top-3 w-4 h-4 text-muted-foreground" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search headlines or publishers" className="w-full rounded-lg border border-input bg-background pl-9 pr-3 py-2.5 text-sm outline-none focus:ring-2 focus:ring-accent/30" /></div><select value={domain} onChange={(event) => setDomain(event.target.value as typeof domain)} className="rounded-lg border border-input bg-background px-3 py-2.5 text-sm"><option>{domainOptions[0]}</option><option>Politics</option><option>Sport</option></select></div><div className="divide-y divide-border">{filtered.map((scan) => { const Icon = verdictIcon[scan.verdict]; return <div key={scan.id} className="p-5 flex items-start gap-4 hover:bg-muted/30 transition-colors"><Icon className={`w-5 h-5 mt-1 shrink-0 ${scan.verdict === "Likely real" ? "text-success" : scan.verdict === "Likely fake" ? "text-destructive" : "text-warning"}`} /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-sm font-semibold text-foreground">{scan.headline}</h2><span className="text-[11px] px-2 py-0.5 rounded-full bg-muted text-muted-foreground">{scan.domain}</span></div><p className="text-xs text-muted-foreground mt-1">{scan.source} · {scan.scannedAt}</p></div><div className="text-right shrink-0"><p className="text-sm font-semibold text-foreground">{scan.confidence}%</p><p className="text-xs text-muted-foreground">confidence</p></div></div> })}</div></div></div></AppLayout>;
}